//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kohaku3
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        public int id_asistencia { get; set; }
        public int clases_id_clases { get; set; }
        public long usuario_id_usuario { get; set; }
        public sbyte validacion_asistencia { get; set; }
        public string novedad { get; set; }
    
        public virtual clases clases { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
