//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kohaku3
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentacion
    {
        public int id_documentacion { get; set; }
        public string nombre_documento { get; set; }
        public string ubicacion_documento { get; set; }
        public long estado_documentacion_id_estado_documentacion { get; set; }
        public long usuario_id_usuario { get; set; }
    
        public virtual estado_documentacion estado_documentacion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
