//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kohaku3
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos
    {
        public long id_pagos { get; set; }
        public long valor { get; set; }
        public string descripcion { get; set; }
        public int numero_clases_pagadas { get; set; }
        public long estado_pago_id_estado_pagos { get; set; }
        public long usuario_id_usuario { get; set; }
    
        public virtual estado_pago estado_pago { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
