//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kohaku3
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.asistencia = new HashSet<asistencia>();
            this.documentacion = new HashSet<documentacion>();
            this.pagos = new HashSet<pagos>();
            this.bitacora = new HashSet<bitacora>();
            this.clases = new HashSet<clases>();
        }
    
        public long id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string numero_identificacion { get; set; }
        public string telefono_fijo { get; set; }
        public string telefono_movil { get; set; }
        public string direccion { get; set; }
        public string correo_electronico { get; set; }
        public int clases_restantes { get; set; }
        public string clave { get; set; }
        public long tipo_usuario_id_tipo_usuario { get; set; }
        public long tipo_documento_idtipo_documento { get; set; }
        public long rango_usuario_idrango_usuario { get; set; }
        public long estado_usuario_idestado_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asistencia> asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentacion> documentacion { get; set; }
        public virtual estado_usuario estado_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagos> pagos { get; set; }
        public virtual rango_usuario rango_usuario { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bitacora> bitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clases> clases { get; set; }
    }
}
